### ISSUE TITLE
[MCHECKSTYLE-53] Cannot copy static resources on windows

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-checkstyle-plugin#189]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** opened **[MCHECKSTYLE-53](https://issues.apache.org/jira/browse/MCHECKSTYLE-53?redirect=false)** and commented

Thread problem...

```
 
Caused by: java.io.FileNotFoundException: ...\images\rss.png (The requested operation cannot be performed on a file with a user-mapped section open)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.(FileOutputStream.java:179)
	at java.io.FileOutputStream.(FileOutputStream.java:131)
	at org.codehaus.plexus.util.FileUtils.copyURLToFile(FileUtils.java:877)
	at org.apache.maven.plugin.checkstyle.ReportResource.copy(ReportResource.java:48)
	at org.apache.maven.plugin.checkstyle.CheckstyleReport.generateReportStatics(CheckstyleReport.java:517)
```

---
No further details from [MCHECKSTYLE-53](https://issues.apache.org/jira/browse/MCHECKSTYLE-53?redirect=false)

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

fixed
