### ISSUE TITLE
[MCHECKSTYLE-102] errors in site for regexp checks with "message" property

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-checkstyle-plugin#200]
**[Benjamin Pochat](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bpochat)** opened **[MCHECKSTYLE-102](https://issues.apache.org/jira/browse/MCHECKSTYLE-102?redirect=false)** and commented

Hi,

It seems that the site built by the CheckStyle plugin is wrong if we use regexp check containing the "message" property.
The error is in the total of violations by rule ("Rules" part). The number of violation is always null for such checks, even if checkstyle shows such violations in the "Details" part.
For instance, i tried this check :

```xml
<module name="Checker">
    <module name="TreeWalker">
        <module name="Regexp">
            <property name="format" value="(.*)(\bEvenement\b)(.*)"/>
            <property name="illegalPattern" value="true"/>
            <property name="ignoreComments" value="true"/>
            <property name="test" value="true"/>
        </module>  
    </module>
</module>
```

A screen shot of the site is given as an attachment.

If I remove the message property in the check definition, the site is correct.

---

**Affects:** 2.2

**Attachments:**
- [screenshot.JPG](https://issues.apache.org/jira/secure/attachment/12714782/screenshot.JPG) (_151.13 kB_)

**Issue Links:**
- [MCHECKSTYLE-103](https://issues.apache.org/jira/browse/MCHECKSTYLE-103) Error in site whith 2 Regexp checks
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Have anyone tried this using one of the newer version of maven-checkstyle-plugin?

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

No feedback, so closing it.
Btw, with this xml I get the following exception:

```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Property 'test' in module Regexp does not exist, please check the documentation
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:142)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:168)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:184)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:158)
	... 24 more
```

It's not a valid example anymore, a lot has changed since then.
