### ISSUE TITLE
[MCHECKSTYLE-159] Optional treeWalker.cacheFile property must not be required

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-checkstyle-plugin#210]
**[tinne](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tinne)** opened **[MCHECKSTYLE-159](https://issues.apache.org/jira/browse/MCHECKSTYLE-159?redirect=false)** and commented

Given a custom checkstyle configuration, checkstyle requires the property cacheFile to the TreeWalker module be configured, thus, the following configuration cannot go without the property line:

\<module name="Checker">
[...]
\<module name="TreeWalker">
\<property name="cacheFile" value="${cachefile}"/>
[...]
\</module>
[...]
\</module>

In case it is omitted, the tool exits with the following stack trace (shortened, regarding version 2.6):

[INFO] Error during page generation

Embedded error: Error rendering Maven report: Failed during checkstyle execution
missing key 'cacheFile' in TreeWalker
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error during page generation
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
at
[...]
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: missing key 'cacheFile' in TreeWalker
at com.puppycrawl.tools.checkstyle.DefaultConfiguration.getAttribute(DefaultConfiguration.java:74)
at org.apache.maven.plugin.checkstyle.DefaultCheckstyleExecutor.getConfiguration(DefaultCheckstyleExecutor.java:270)
... 28 more

Due to checkstyle documentation, the property is optional, and no cachefile will be used in case it is not specified (cf. http://checkstyle.sourceforge.net/config.html#TreeWalker). Also, cacheFile can be specified in the pom, thus it should be substituted anyway.

Workaround:

Add \<configuration/>-Entry

\<propertyExpansion>
cacheFile=${project.build.directory}/checkstyle-cachefile
\</propertyExpansion>
and use the above property line and a special maven build version of the checkstyle configuration file.

---

**Affects:** 2.6, 2.7

4 votes, 7 watchers

**Comment by jira-importer** [comment]
**[Filip van Laenen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=filipvanlaenen)** commented

There's a small type in the Checkstyle configuration: the value of the property should have a capital F like this in order for the work-around to work:

\<module name="Checker">
[...]
\<module name="TreeWalker">
\<property name="cacheFile" value="${cacheFile}"/>
[...]
\</module>
[...]
\</module>

**Comment by jira-importer** [comment]
**[Pierre Cardoso](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gonnalose)** commented

Just wanted to say I only have this issue with version 2.7, not 2.6
