### ISSUE TITLE
[MCHECKSTYLE-189] Unable to instantiate DoubleCheckedLockingCheck exception after upgrading from version 2.9.1 to 2.10

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-checkstyle-plugin#214]
**[Michael Heuer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=heuermh)** opened **[MCHECKSTYLE-189](https://issues.apache.org/jira/browse/MCHECKSTYLE-189?redirect=false)** and commented

After upgrading from version 3.9.1 to version 3.10

$ mvn -e site
...
Error during page generation: Error rendering Maven report: Failed during checkstyle configuration: cannot initialize module TreeWalker - Unable to instantiate DoubleCheckedLocking: Unable to instantiate DoubleCheckedLockingCheck -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.2:site (default-site) on project dsh-midi-cytoscape3-app: Error during page generation
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error during page generation
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:143)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
... 19 more
Caused by: org.apache.maven.doxia.siterenderer.RendererException: Error rendering Maven report: Failed during checkstyle configuration
at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:233)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:319)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:135)
at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
... 21 more
Caused by: org.apache.maven.reporting.MavenReportException: Failed during checkstyle configuration
at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeReport(AbstractCheckstyleReport.java:260)
at org.apache.maven.plugin.checkstyle.CheckstyleReport.executeReport(CheckstyleReport.java:339)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:196)
at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:219)
... 25 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - Unable to instantiate DoubleCheckedLocking
at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:178)
at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:184)
at org.apache.maven.plugin.checkstyle.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:172)
at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeReport(AbstractCheckstyleReport.java:245)
... 28 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate DoubleCheckedLocking
at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:155)
at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:161)
at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:184)
at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:157)
... 31 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate DoubleCheckedLockingCheck
at com.puppycrawl.tools.checkstyle.PackageObjectFactory.doMakeObject(PackageObjectFactory.java:98)
at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:152)
... 34 more

---

**Affects:** 2.10

**Attachments:**
- [mcheckstyle188.tar.gz](https://issues.apache.org/jira/secure/attachment/12714761/mcheckstyle188.tar.gz) (_3.55 kB_)

**Issue Links:**
- [MYFACES-3995](https://issues.apache.org/jira/browse/MYFACES-3995) Remove DoubleCheckedLockingCheck from checkstyle rules

1 votes, 4 watchers

**Comment by jira-importer** [comment]
**[Nick Stolwijk](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nstolwijk)** commented

As you can see at https://jira.codehaus.org/browse/MCHECKSTYLE-181 Checkstyle has been upgraded to version 5.6 in the new plugin version.

Unfortunately, Winrar wouldn't open your attachment, so I cannot check which checkstyle configuration you use. Could it be you have your own configuration and didn't update it to be compatible with Checkstyle 5.6?

**Comment by jira-importer** [comment]
**[Nick Stolwijk](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nstolwijk)** commented

Ah, also see http://sourceforge.net/p/checkstyle/bugs/681/. It seems Checkstyle 5.6 contains a bug, that the sun_checks.xml still contains this check. Unfortunately, the sun_checks is the default for the Maven Checkstyle plugin.

See http://maven.apache.org/plugins/maven-checkstyle-plugin/checkstyle-mojo.html#configLocation for how to use your own.

**Comment by jira-importer** [comment]
**[Michael Heuer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=heuermh)** commented

Tar via cygwin should work on windows.

The problem is in fact with a custom configuration checkstyle.xml which includes

```xml
<module name="DoubleCheckedLocking"/>
```

The release notes for Checkstyle 5.5 --> 5.6 say

> Removed the DoubleCheckedLocking check, as in Java 5 (and beyond), using the volatile keyword addresses the issue. See here for more details.

The release notes for Maven Checkstyle Plugin 2.9.1 --> 2.10 do not mention this change.

I think both projects have failed with regards to semantic versioning -- even though this is not a strict binary-incompatible change, it is a configuration-incompatible change.  Updating a minor version of a maven plugin should not cause existing projects to break.

**Comment by jira-importer** [comment]
**[Nick Stolwijk](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nstolwijk)** commented

I concur on you with that. It would be nicer if Checkstyle removed the functionality of the class and displayed a warning when instantiating the class.

At least you can get it to work again now.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Hi,

My point on this, as a Maven developer and a Checkstyle user, is that the Checkstyle project should not have removed a check in a minor release.

All Checkstyle configuration files that are included in Maven Checkstyle Plugin was updated in version 2.10, so that they do not include the DoubleCheckedLocking check. Only users that have their own configuration file are affected.

The release log for Maven Checkstyle Plugin mentions that it has upgraded to Checkstyle 5.6. We never include items from the Checkstyle project's release log in ours. Interested users should check the Checkstyle project for that.

Yes, we could have made the plugin version 3.0, but we didn't. This can of course be debated, but will not change the past.

**Comment by jira-importer** [comment]
**[Michael Heuer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=heuermh)** commented

Fair enough, thanks.
