### ISSUE TITLE
[MCHECKSTYLE-324] cleanup debug "error messages" when using inline checkstyle rules (on windows)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-checkstyle-plugin#240]
**[Romain Manni-Bucau](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=romain.manni-bucau)** opened **[MCHECKSTYLE-324](https://issues.apache.org/jira/browse/MCHECKSTYLE-324?redirect=false)** and commented

Seems

```
configLocation = rulesFiles.getAbsolutePath();
```

should be

```
configLocation = rulesFiles.toURI().toURL().toExternalForm();
```

should use a URI instead of a file path for windows otherwise you get

```
[DEBUG] URLResourceLoader: Exception when looking for 'C:\cygwin\drone\src\github.com\rmannibucau\crest\target\checkstyle-rules.xml' at ''

java.net.MalformedURLException: unknown protocol: c

	at java.net.URL.<init>(URL.java:600)

	at java.net.URL.<init>(URL.java:490)

	at java.net.URL.<init>(URL.java:439)

	at org.codehaus.plexus.resource.loader.URLResourceLoader.getResource(URLResourceLoader.java:71)

	at org.codehaus.plexus.resource.DefaultResourceManager.getResource(DefaultResourceManager.java:159)

	at org.codehaus.plexus.resource.DefaultResourceManager.getResourceAsFile(DefaultResourceManager.java:91)

	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.getConfigFile(DefaultCheckstyleExecutor.java:822)

	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.getConfiguration(DefaultCheckstyleExecutor.java:378)

	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:217)

	at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:538)
```

---

**Issue Links:**
- [MCHECKSTYLE-220](https://issues.apache.org/jira/browse/MCHECKSTYLE-220) Debug shows unnecessary stacktrace with java.net.MalformedURLException: no protocol: LICENSE.txt
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please provide a sample project.
