### ISSUE TITLE
[MCHECKSTYLE-12] Checkstyle report generation problem

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-checkstyle-plugin#374]
**[Yue Ni](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nybon)** opened **[MCHECKSTYLE-12](https://issues.apache.org/jira/browse/MCHECKSTYLE-12?redirect=false)** and commented

I use maven checkstyle plugin(2.0-beta-1) to generate a checkstyle report. I configed it in the pom.xml and enter "mvn site:site" to generate the report. But I got a NullPointerExcetpion just like the error described in http://pastebin.ca/30802.
The stack trace is:

[INFO] Generate "Checkstyle" report.
[INFO] ----------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ----------------------------------------------------------------------------

---

constituent[0]: file:/D:/maven2/bin/../lib/maven-core-2.0.jar
constituent[1]: file:/D:/maven2/bin/../lib/maven-plugin-parameter-documenter-2.0.jar
constituent[2]: file:/D:/maven2/bin/../lib/maven-model-2.0.jar
constituent[3]: file:/D:/maven2/bin/../lib/maven-profile-2.0.jar
constituent[4]: file:/D:/maven2/bin/../lib/maven-project-2.0-1.jar
constituent[5]: file:/D:/maven2/bin/../lib/maven-error-diagnostics-2.0.jar
constituent[6]: file:/D:/maven2/bin/../lib/plexus-interactivity-api-1.0-alpha-4.jar
constituent[7]: file:/D:/maven2/bin/../lib/wagon-http-lightweight-1.0-alpha-5.jarjava.lang.NullPointerException
at org.apache.maven.usability.diagnostics.DiagnosisUtils.appendRootCauseIfPresentAndUnique(DiagnosisUtils.java:89)
at org.apache.maven.usability.diagnostics.ErrorDiagnostics$PuntErrorDiagnoser.diagnose(ErrorDiagnostics.java:132)
at org.apache.maven.usability.diagnostics.ErrorDiagnostics.diagnose(ErrorDiagnostics.java:104)
at org.apache.maven.DefaultMaven.logDiagnostics(DefaultMaven.java:693)
at org.apache.maven.DefaultMaven.logFatal(DefaultMaven.java:627)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:143)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---
No further details from [MCHECKSTYLE-12](https://issues.apache.org/jira/browse/MCHECKSTYLE-12?redirect=false)

**Comment by jira-importer** [comment]
**[Joakim Erdfelt](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=joakime)** commented

The comment mentions the URL: http://pastebin.ca/30802

The stack traces mentioned at that URL point to 2 different errors.

First one is a commons-logging error with Jdk14Logger.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

Added a runtime dep on log4j to the checkstyle plugin POM to avoid the commons-logging problem, and made the DiagnosisUtils more resilient to null error parameters.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

forgot fix version
