### ISSUE TITLE
[MCHECKSTYLE-15] Exception: Can't find resource bundle for current bundle

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-checkstyle-plugin#377]
**[Michael Böckling](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=buddycasino)** opened **[MCHECKSTYLE-15](https://issues.apache.org/jira/browse/MCHECKSTYLE-15?redirect=false)** and commented

When I try to execute mvn site with checkstyle configured in my POM, it throws an exception saying it can't find the resource bundle for my locale. Explicitly setting \<locales>en\<locales> in my POM has not effect.

Console:

[INFO] [site:site]
[INFO] -------------------------------------------------------------------------
&mdash;
[ERROR] FATAL ERROR
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Can't find bundle for base name checkstyle-report, locale de_CH
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Trace
java.util.MissingResourceException: Can't find bundle for base name checkstyle-r
eport, locale de_CH
at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle
.java:804)
at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:773)
at java.util.ResourceBundle.getBundle(ResourceBundle.java:661)
at org.apache.maven.plugin.checkstyle.CheckstyleReport.getBundle(Checkst
yleReport.java:539)
at org.apache.maven.plugin.checkstyle.CheckstyleReport.getName(Checkstyl
eReport.java:201)
at org.apache.maven.plugins.site.ReportComparator.compare(ReportComparat
or.java:40)
at java.util.Arrays.mergeSort(Arrays.java:1278)
at java.util.Arrays.sort(Arrays.java:1219)
at java.util.Collections.sort(Collections.java:155)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:240)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:399)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:519)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLi
fecycle(DefaultLifecycleExecutor.java:469)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:448)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:301)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:268)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:137)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:316)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:113)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---
No further details from [MCHECKSTYLE-15](https://issues.apache.org/jira/browse/MCHECKSTYLE-15?redirect=false)

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

wrapped the getBundle(..) method with a new instance-level method that uses a try/catch to report failures in loading a given locale's resource bundle, and defaults over to Locale.ENGLISH when necessary.

**Comment by jira-importer** [comment]
**[domi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=arachus)** commented

I have the same problem - the fix seems not yet to be published...

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

it hasn't been released yet, no.
