### ISSUE TITLE
[MCHECKSTYLE-147] Upgrading from 2.4 to 2.6 causes failure during checkstyle configuration

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-checkstyle-plugin#474]
**[Steve Gorczyca](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sgorczyca)** opened **[MCHECKSTYLE-147](https://issues.apache.org/jira/browse/MCHECKSTYLE-147?redirect=false)** and commented

Upgrading from plugin version 2.4 to 2.6 then trying to run mvn site, the build fails because it can't find our suppressions file, even though the debug information indicates that it is correctly found and the file is correctly extracted to target/checkstyle-suppressions.xml

Relevant part of the build output:

[INFO] Generating "Project Plugins" report.
[DEBUG] maven-jxr-plugin: resolved to version 2.1 from repository central
[DEBUG] maven-surefire-report-plugin: resolved to version 2.4.3 from repository                                                                       central
[DEBUG] Adding managed dependencies for org.apache.maven.plugins:maven-surefire-                                                                      report-plugin
[DEBUG]   org.apache.maven.surefire:surefire-api:jar:2.4.3
[DEBUG]   org.apache.maven.surefire:surefire-booter:jar:2.4.3
[DEBUG]   org.codehaus.plexus:plexus-utils:jar:1.5.1
[DEBUG] Multipage report: 0 subreports
[DEBUG] Velocimacro : added #link(  href name ) : source = org/apache/maven/doxi                                                                      a/siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #banner(  banner id ) : source = org/apache/maven/do                                                                      xia/siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #links(  links ) : source = org/apache/maven/doxia/s                                                                      iterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #breadcrumbs(  breadcrumbs ) : source = org/apache/m                                                                      aven/doxia/siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #displayTree(  display item ) : source = org/apache/                                                                      maven/doxia/siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #menuItem(  item ) : source = org/apache/maven/doxia                                                                      /siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #mainMenu(  menus ) : source = org/apache/maven/doxi                                                                      a/siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #copyright(  ) : source = org/apache/maven/doxia/sit                                                                      erenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #publishDate(  position publishDate version ) : sour                                                                      ce = org/apache/maven/doxia/siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #poweredByLogo(  poweredBy ) : source = org/apache/m                                                                      aven/doxia/siterenderer/resources/default-site.vm
[DEBUG] Generating C:\work\trunk\wordnet-dictionary\target\site\checkstyle.html
[INFO] Generating "Checkstyle" report.
[WARNING] Deprecated API called - not org.apache.maven.doxia.sink.Sink instance                                                                       and no SinkFactory available. Please update this plugin.
[DEBUG] executeCheckstyle start headerLocation : LICENSE.txt
[DEBUG] The resource 'build-tools/checkstyle_suppressions.xml' was not found wit                                                                      h resourceLoader org.codehaus.plexus.resource.loader.FileResourceLoader.
[DEBUG] The resource 'build-tools/checkstyle_suppressions.xml' was not found wit                                                                      h resourceLoader org.codehaus.plexus.resource.loader.JarResourceLoader.
[DEBUG] The resource 'build-tools/checkstyle_suppressions.xml' was found as jar:                                                                      file:/C:/mavenRepo/com/companyName/build-tools/1.2/build-tools-1.2.jar!/build-                                                                      tools/checkstyle_suppressions.xml.
[DEBUG] Adding the outputDirectory file:/C:/work/trunk/wordnet-dictionary/target                                                                      /classes/ to the Checkstyle class path
[DEBUG] Adding the outputDirectory file:/C:/work/trunk/wordnet-dictionary/target                                                                      /test-classes/ to the Checkstyle class path
[DEBUG] request.getConfigLocation() build-tools/checkstyle_checks.xml
[DEBUG] The resource 'build-tools/checkstyle_checks.xml' was not found with reso                                                                      urceLoader org.codehaus.plexus.resource.loader.FileResourceLoader.
[DEBUG] The resource 'build-tools/checkstyle_checks.xml' was not found with reso                                                                      urceLoader org.codehaus.plexus.resource.loader.JarResourceLoader.
[DEBUG] The resource 'build-tools/checkstyle_checks.xml' was found as jar:file:/                                                                      C:/mavenRepo/com/companyName/build-tools/1.2/build-tools-1.2.jar!/build-tools/                                                                      checkstyle_checks.xml.
[DEBUG] headerLocation LICENSE.txt
[DEBUG] The resource 'LICENSE.txt' was not found with resourceLoader org.codehau                                                                      s.plexus.resource.loader.FileResourceLoader.
[DEBUG] The resource 'LICENSE.txt' was not found with resourceLoader org.codehau                                                                      s.plexus.resource.loader.JarResourceLoader.
[DEBUG] The resource 'LICENSE.txt' was found as jar:file:/C:/mavenRepo/org/apach                                                                      e/maven/plugins/maven-checkstyle-plugin/2.6/maven-checkstyle-plugin-2.6.jar!/LIC                                                                      ENSE.txt.
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error during page generation

Embedded error: Error rendering Maven report: Failed during checkstyle configura                                                                      tion
checkstyle.suppressions.file (The system cannot find the file specified)
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error during page genera                                                                      tion
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa                                                                      ultLifecycleExecutor.java:719)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLi                                                                      fecycle(DefaultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau                                                                      ltLifecycleExecutor.java:535)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan                                                                      dleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen                                                                      ts(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi                                                                      fecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:6                                                                      0)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error during page gen                                                                      eration
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:105)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi                                                                      nManager.java:490)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa                                                                      ultLifecycleExecutor.java:694)
... 17 more
Caused by: org.apache.maven.doxia.siterenderer.RendererException: Error renderin                                                                      g Maven report: Failed during checkstyle configuration
at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(R                                                                      eportDocumentRenderer.java:149)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(                                                                      DefaultSiteRenderer.java:269)
at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(Defaul                                                                      tSiteRenderer.java:101)
at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:133                                                                      )
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:100)
... 19 more
Caused by: org.apache.maven.reporting.MavenReportException: Failed during checks                                                                      tyle configuration
at org.apache.maven.plugin.checkstyle.CheckstyleReport.executeReport(Che                                                                      ckstyleReport.java:593)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMaven                                                                      Report.java:190)
at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMaven                                                                      Report.java:144)
at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(R                                                                      eportDocumentRenderer.java:139)
... 23 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initi                                                                      alize module SuppressionFilter - Cannot set property 'file' in module Suppressio                                                                      nFilter to 'checkstyle.suppressions.file': unable to find checkstyle.suppression                                                                      s.file
at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:177)
at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(Automatic                                                                      Bean.java:207)
at org.apache.maven.plugin.checkstyle.DefaultCheckstyleExecutor.executeC                                                                      heckstyle(DefaultCheckstyleExecutor.java:174)
at org.apache.maven.plugin.checkstyle.CheckstyleReport.executeReport(Che                                                                      ckstyleReport.java:578)
... 26 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Cannot set p                                                                      roperty 'file' in module SuppressionFilter to 'checkstyle.suppressions.file': un                                                                      able to find checkstyle.suppressions.file
at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(Automatic                                                                      Bean.java:175)
at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:156)
... 29 more
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyU                                                                      tilsBean.java:1773)
at org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(Prop                                                                      ertyUtilsBean.java:1759)
at org.apache.commons.beanutils.BeanUtilsBean.copyProperty(BeanUtilsBean                                                                      .java:447)
at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(Automatic                                                                      Bean.java:172)
... 30 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to fi                                                                      nd checkstyle.suppressions.file
at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.loadSuppre                                                                      ssions(SuppressionsLoader.java:138)
at com.puppycrawl.tools.checkstyle.filters.SuppressionFilter.setFile(Sup                                                                      pressionFilter.java:49)
... 38 more
Caused by: java.io.FileNotFoundException: checkstyle.suppressions.file (The syst                                                                      em cannot find the file specified)
at java.io.FileInputStream.open(Native Method)
at java.io.FileInputStream.\<init>(Unknown Source)
at java.io.FileInputStream.\<init>(Unknown Source)
at com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.loadSuppre                                                                      ssions(SuppressionsLoader.java:135)
... 39 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14 seconds
[INFO] Finished at: Wed Oct 06 11:42:30 EDT 2010
[INFO] Final Memory: 97M/369M
[INFO] ------------------------------------------------------------------------

Our build-tools/pom.xml:

\<project xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
http://maven.apache.org/xsd/maven-4.0.0.xsd">

\<modelVersion>4.0.0\</modelVersion>
\<groupId>com.companyName\</groupId>
\<artifactId>build-tools\</artifactId>
\<packaging>jar\</packaging>
\<version>1.2\</version>
\<name>companyName Build Tools\</name>

\<build>
\<defaultGoal>install\</defaultGoal>
\</build>
\</project>

Relevant parts of our 'main' project pom.xml:

\<project>
\<modelVersion>4.0.0\</modelVersion>
\<groupId>com.companyName\</groupId>
\<artifactId>system\</artifactId>
\<packaging>pom\</packaging>
\<version>2.4\</version>
\<modules>
\<module>build-tools\</module>
\<module>wordnet-dictionary\</module>
\</modules>
...
\<build>
\<plugins>
\<plugin>
\<groupId>org.apache.maven.plugins\</groupId>
\<artifactId>maven-checkstyle-plugin\</artifactId>
\<version>2.6\</version>
\<dependencies>
\<dependency>
\<groupId>com.securboration\</groupId>
\<artifactId>build-tools\</artifactId>
\<version>1.2\</version>
\</dependency>
\</dependencies>
\</plugin>
\</plugins>
\</build>
\<reporting>
\<plugins>
\<plugin>
\<groupId>org.apache.maven.plugins\</groupId>
\<artifactId>maven-checkstyle-plugin\</artifactId>
\<version>2.6\</version>
\<configuration>
\<configLocation>build-tools/checkstyle_checks.xml\</configLocation>
\<suppressionsLocation>build-tools/checkstyle_suppressions.xml\</suppressionsLocation>
\<includeTestSourceDirectory>true\</includeTestSourceDirectory>
\</configuration> 
\</plugin>
\</plugins>
\</reporting>
\</project>

Our module pom.xml in which the failure occurs:

\<project xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
http://maven.apache.org/xsd/maven-4.0.0.xsd">

\<parent>
\<groupId>com.companyName\</groupId>
\<artifactId>system\</artifactId>
\<version>2.4\</version>
\</parent>

\<modelVersion>4.0.0\</modelVersion>
\<groupId>com.companyName\</groupId>
\<artifactId>wordnet-dictionary\</artifactId>
\<packaging>jar\</packaging>
\<version>1.0\</version>
\<name>Wordnet Dictionary\</name>

\</project>

---

**Affects:** 2.6

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Can you please try 2.7-SNAPSHOT. This might be related to MCHECKSTYLE-149.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

No feedback from reporter.
