### ISSUE TITLE
[MCHECKSTYLE-146] mvn checkstyle:checkstyle KO, Unable to find the mojo, org/apache/maven/doxia/logging/Log

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-checkstyle-plugin#475]
**[Olivier Ribardière](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ribardo0)** opened **[MCHECKSTYLE-146](https://issues.apache.org/jira/browse/MCHECKSTYLE-146?redirect=false)** and commented

Since checkstyle 2.6 was released on the maven respository, mvn checkstyle:checkstyle fails on few environments.

Here is the error I have :

```
[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'checkstyle'.
[INFO] org.apache.maven.plugins: checking for updates from central
[WARNING] repository metadata for: 'org.apache.maven.plugins' could not be retrieved from repository: central due to an error: Error transferring file
[INFO] Repository 'central' will be blacklisted
[INFO] ------------------------------------------------------------------------
[INFO] Building CDN - Composant - Maven Dependency Matrix
[INFO]    task-segment: [checkstyle:checkstyle]
[INFO] ------------------------------------------------------------------------
-----------------------------------------------------
this realm = app0.child-container[org.apache.maven.plugins:maven-checkstyle-plugin]
urls[0] = file:/usr/users/apachsvn/.m2/repository/org/apache/maven/plugins/maven-checkstyle-plugin/2.6/maven-checkstyle-plugin-2.6.jar
urls[1] = file:/usr/users/apachsvn/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.jar
urls[2] = file:/usr/users/apachsvn/.m2/repository/org/apache/maven/reporting/maven-reporting-impl/2.1/maven-reporting-impl-2.1.jar
urls[3] = file:/usr/users/apachsvn/.m2/repository/org/apache/maven/doxia/doxia-core/1.1.2/doxia-core-1.1.2.jar
urls[4] = file:/usr/users/apachsvn/.m2/repository/xerces/xercesImpl/2.8.1/xercesImpl-2.8.1.jar
urls[5] = file:/usr/users/apachsvn/.m2/repository/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar
urls[6] = file:/usr/users/apachsvn/.m2/repository/commons-lang/commons-lang/2.1/commons-lang-2.1.jar
urls[7] = file:/usr/users/apachsvn/.m2/repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar
urls[8] = file:/usr/users/apachsvn/.m2/repository/commons-logging/commons-logging/1.0.3/commons-logging-1.0.3.jar
urls[9] = file:/usr/users/apachsvn/.m2/repository/commons-codec/commons-codec/1.2/commons-codec-1.2.jar
urls[10] = file:/usr/users/apachsvn/.m2/repository/org/apache/maven/doxia/doxia-site-renderer/1.1.3/doxia-site-renderer-1.1.3.jar
urls[11] = file:/usr/users/apachsvn/.m2/repository/org/apache/maven/doxia/doxia-decoration-model/1.1.3/doxia-decoration-model-1.1.3.jar
urls[12] = file:/usr/users/apachsvn/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.1.3/doxia-module-xhtml-1.1.3.jar
urls[13] = file:/usr/users/apachsvn/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.1.3/doxia-module-fml-1.1.3.jar
urls[14] = file:/usr/users/apachsvn/.m2/repository/org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.jar
urls[15] = file:/usr/users/apachsvn/.m2/repository/org/codehaus/plexus/plexus-velocity/1.1.8/plexus-velocity-1.1.8.jar
urls[16] = file:/usr/users/apachsvn/.m2/repository/org/apache/velocity/velocity/1.5/velocity-1.5.jar
urls[17] = file:/usr/users/apachsvn/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
urls[18] = file:/usr/users/apachsvn/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar
urls[19] = file:/usr/users/apachsvn/.m2/repository/commons-validator/commons-validator/1.2.0/commons-validator-1.2.0.jar
urls[20] = file:/usr/users/apachsvn/.m2/repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar
urls[21] = file:/usr/users/apachsvn/.m2/repository/commons-digester/commons-digester/1.6/commons-digester-1.6.jar
urls[22] = file:/usr/users/apachsvn/.m2/repository/org/apache/maven/shared/maven-doxia-tools/1.2.1/maven-doxia-tools-1.2.1.jar
urls[23] = file:/usr/users/apachsvn/.m2/repository/commons-io/commons-io/1.4/commons-io-1.4.jar
urls[24] = file:/usr/users/apachsvn/.m2/repository/org/codehaus/plexus/plexus-resources/1.0-alpha-7/plexus-resources-1.0-alpha-7.jar
urls[25] = file:/usr/users/apachsvn/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.jar
urls[26] = file:/usr/users/apachsvn/.m2/repository/checkstyle/checkstyle/5.0/checkstyle-5.0.jar
urls[27] = file:/usr/users/apachsvn/.m2/repository/antlr/antlr/2.7.6/antlr-2.7.6.jar
urls[28] = file:/usr/users/apachsvn/.m2/repository/commons-beanutils/commons-beanutils-core/1.7.0/commons-beanutils-core-1.7.0.jar
urls[29] = file:/usr/users/apachsvn/.m2/repository/com/google/collections/google-collections/0.9/google-collections-0.9.jar
Number of imports: 6
import: org.codehaus.classworlds.Entry@4891bb28
import: org.codehaus.classworlds.Entry@f8e44ca4
import: org.codehaus.classworlds.Entry@c51bc9e7
import: org.codehaus.classworlds.Entry@bece5185
import: org.codehaus.classworlds.Entry@3fee8e37
import: org.codehaus.classworlds.Entry@3fee19d8


this realm = plexus.core
urls[0] = file:/usr/users/apachsvn/maven/lib/maven-2.0.9-uber.jar
Number of imports: 6
import: org.codehaus.classworlds.Entry@4891bb28
import: org.codehaus.classworlds.Entry@f8e44ca4
import: org.codehaus.classworlds.Entry@c51bc9e7
import: org.codehaus.classworlds.Entry@bece5185
import: org.codehaus.classworlds.Entry@3fee8e37
import: org.codehaus.classworlds.Entry@3fee19d8
-----------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Internal error in the plugin manager executing goal 'org.apache.maven.plugins:maven-checkstyle-plugin:2.6:checkstyle': Unable to find the mojo 'org.apache.maven.plugins:maven-checkstyle-plugin:2.6:checkstyle' in the plugin 'org.apache.maven.plugins:maven-checkstyle-plugin'
org/apache/maven/doxia/logging/Log
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24 seconds
[INFO] Finished at: Thu Sep 30 16:31:57 CEST 2010
[INFO] Final Memory: 18M/650M
[INFO] ------------------------------------------------------------------------
```

If I run the same using mvn -e, here is the detailed trace :

```
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Internal error in the plugin manager executing goal 'org.apache.maven.plugins:maven-checkstyle-plugin:2.6:checkstyle': Unable to find the mojo 'org.apache.maven.plugins:maven-checkstyle-plugin:2.6:checkstyle' in the plugin 'org.apache.maven.plugins:maven-checkstyle-plugin'
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:562)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:512)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:482)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.PluginManagerException: Unable to find the mojo 'org.apache.maven.plugins:maven-checkstyle-plugin:2.6:checkstyle' in the plugin 'org.apache.maven.plugins:maven-checkstyle-plugin'
        at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:618)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:429)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
        ... 16 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.apache.maven.plugin.Mojoorg.apache.maven.plugins:maven-checkstyle-plugin:2.6:checkstyle', it could not be started
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:339)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
        at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:609)
        ... 18 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLifecycleException: Error starting component
        at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:109)
        at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:95)
        at org.codehaus.plexus.component.manager.PerLookupComponentManager.getComponent(PerLookupComponentManager.java:48)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
        ... 20 more
Caused by: org.codehaus.plexus.personality.plexus.lifecycle.phase.PhaseExecutionException: Error composing component
        at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:33)
        at org.codehaus.plexus.lifecycle.AbstractLifecycleHandler.start(AbstractLifecycleHandler.java:101)
        at org.codehaus.plexus.component.manager.AbstractComponentManager.startComponentLifecycle(AbstractComponentManager.java:105)
        ... 23 more
Caused by: org.codehaus.plexus.component.composition.CompositionException: Composition failed of field siteRenderer in object of type org.apache.maven.plugin.checkstyle.CheckstyleReport because the requirement ComponentRequirement{role='org.apache.maven.doxia.siterenderer.Renderer', roleHint='null', fieldName='siteRenderer'} was missing
        at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentComposer.java:154)
        at org.codehaus.plexus.component.composition.FieldComponentComposer.assembleComponent(FieldComponentComposer.java:73)
        at org.codehaus.plexus.component.composition.DefaultComponentComposerManager.assembleComponent(DefaultComponentComposerManager.java:68)
        at org.codehaus.plexus.DefaultPlexusContainer.composeComponent(DefaultPlexusContainer.java:1486)
        at org.codehaus.plexus.personality.plexus.lifecycle.phase.CompositionPhase.execute(CompositionPhase.java:29)
        ... 25 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Unable to lookup component 'org.apache.maven.doxia.siterenderer.Renderer', it could not be created
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:335)
        at org.codehaus.plexus.component.composition.FieldComponentComposer.assignRequirementToField(FieldComponentComposer.java:129)
        ... 29 more
Caused by: org.codehaus.plexus.component.factory.ComponentInstantiationException: Could not instanciate component: role: 'org.apache.maven.doxia.siterenderer.Renderer', implementation: 'org.apache.maven.doxia.siterenderer.DefaultSiteRenderer', role hint: 'default'
        at org.codehaus.plexus.component.factory.java.JavaComponentFactory.makeException(JavaComponentFactory.java:77)
        at org.codehaus.plexus.component.factory.java.JavaComponentFactory.newInstance(JavaComponentFactory.java:62)
        at org.codehaus.plexus.DefaultPlexusContainer.createComponentInstance(DefaultPlexusContainer.java:1464)
        at org.codehaus.plexus.component.manager.AbstractComponentManager.createComponentInstance(AbstractComponentManager.java:93)
        at org.codehaus.plexus.component.manager.ClassicSingletonComponentManager.getComponent(ClassicSingletonComponentManager.java:92)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:331)
        ... 30 more
Caused by: java.lang.NoClassDefFoundError: org/apache/maven/doxia/logging/Log
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2357)
        at java.lang.Class.getConstructor0(Class.java:2671)
        at java.lang.Class.newInstance0(Class.java:321)
        at java.lang.Class.newInstance(Class.java:303)
        at org.codehaus.plexus.component.factory.java.JavaComponentFactory.newInstance(JavaComponentFactory.java:44)
        ... 34 more

```

---

**Affects:** 2.6

**Issue Links:**
- [MPMD-140](https://issues.apache.org/jira/browse/MPMD-140) Require Maven 2.2.1

- [MSITE-641](https://issues.apache.org/jira/browse/MSITE-641) Require Maven 2.2.1

2 votes, 1 watchers

**Comment by jira-importer** [comment]
**[Michael Neifeld](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=newfield)** commented

I also face this problem :

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building JAC
[INFO]    task-segment: [site]
[INFO] ------------------------------------------------------------------------

---

this realm = app0.child-container[org.apache.maven.plugins:maven-checkstyle-plugin]
urls[0] = file:/d:/maven_repository/org/apache/maven/plugins/maven-checkstyle-plugin/2.6/maven-checkstyle-plugin-2.6.jar
urls[1] = file:/d:/maven_repository/org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.jar
urls[2] = file:/d:/maven_repository/org/apache/maven/reporting/maven-reporting-impl/2.1/maven-reporting-impl-2.1.jar
urls[3] = file:/d:/maven_repository/org/apache/maven/doxia/doxia-core/1.1.2/doxia-core-1.1.2.jar
urls[4] = file:/d:/maven_repository/xerces/xercesImpl/2.8.1/xercesImpl-2.8.1.jar
urls[5] = file:/d:/maven_repository/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar
urls[6] = file:/d:/maven_repository/commons-lang/commons-lang/2.1/commons-lang-2.1.jar
urls[7] = file:/d:/maven_repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar
urls[8] = file:/d:/maven_repository/commons-logging/commons-logging/1.0.3/commons-logging-1.0.3.jar
urls[9] = file:/d:/maven_repository/commons-codec/commons-codec/1.2/commons-codec-1.2.jar
urls[10] = file:/d:/maven_repository/org/apache/maven/doxia/doxia-site-renderer/1.1.3/doxia-site-renderer-1.1.3.jar
urls[11] = file:/d:/maven_repository/org/apache/maven/doxia/doxia-decoration-model/1.1.3/doxia-decoration-model-1.1.3.jar
urls[12] = file:/d:/maven_repository/org/apache/maven/doxia/doxia-module-xhtml/1.1.3/doxia-module-xhtml-1.1.3.jar
urls[13] = file:/d:/maven_repository/org/apache/maven/doxia/doxia-module-fml/1.1.3/doxia-module-fml-1.1.3.jar
urls[14] = file:/d:/maven_repository/org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.jar
urls[15] = file:/d:/maven_repository/org/codehaus/plexus/plexus-velocity/1.1.8/plexus-velocity-1.1.8.jar
urls[16] = file:/d:/maven_repository/org/apache/velocity/velocity/1.5/velocity-1.5.jar
urls[17] = file:/d:/maven_repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
urls[18] = file:/d:/maven_repository/oro/oro/2.0.8/oro-2.0.8.jar
urls[19] = file:/d:/maven_repository/commons-validator/commons-validator/1.2.0/commons-validator-1.2.0.jar
urls[20] = file:/d:/maven_repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar
urls[21] = file:/d:/maven_repository/commons-digester/commons-digester/1.6/commons-digester-1.6.jar
urls[22] = file:/d:/maven_repository/org/apache/maven/shared/maven-doxia-tools/1.2.1/maven-doxia-tools-1.2.1.jar
urls[23] = file:/d:/maven_repository/commons-io/commons-io/1.4/commons-io-1.4.jar
urls[24] = file:/d:/maven_repository/org/codehaus/plexus/plexus-resources/1.0-alpha-7/plexus-resources-1.0-alpha-7.jar
urls[25] = file:/d:/maven_repository/org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.jar
urls[26] = file:/d:/maven_repository/checkstyle/checkstyle/5.0/checkstyle-5.0.jar
urls[27] = file:/d:/maven_repository/antlr/antlr/2.7.6/antlr-2.7.6.jar
urls[28] = file:/d:/maven_repository/commons-beanutils/commons-beanutils-core/1.7.0/commons-beanutils-core-1.7.0.jar
urls[29] = file:/d:/maven_repository/com/google/collections/google-collections/0.9/google-collections-0.9.jar
Number of imports: 6
import: org.codehaus.classworlds.Entry@4891bb28
import: org.codehaus.classworlds.Entry@f8e44ca4
import: org.codehaus.classworlds.Entry@c51bc9e7
import: org.codehaus.classworlds.Entry@bece5185
import: org.codehaus.classworlds.Entry@3fee8e37
import: org.codehaus.classworlds.Entry@3fee19d8

this realm = plexus.core
urls[0] = file:/D:/apache-maven-2.0.9/lib/maven-2.0.9-uber.jar
Number of imports: 6
import: org.codehaus.classworlds.Entry@4891bb28
import: org.codehaus.classworlds.Entry@f8e44ca4
import: org.codehaus.classworlds.Entry@c51bc9e7
import: org.codehaus.classworlds.Entry@bece5185
import: org.codehaus.classworlds.Entry@3fee8e37
import: org.codehaus.classworlds.Entry@3fee19d8

---

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error getting reports from the plugin 'org.apache.maven.plugins:maven-checkstyle-plugin': Unable to find the mojo 'org.apache.maven.plugins:maven-checkstyle-plugin:2.6:checkstyle' in the plugin 'org.apache.maven.plugins:maven-checkstyle-plugin'
org.apache.maven.doxia.logging.Log
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6 seconds
[INFO] Finished at: Thu May 12 14:34:36 IDT 2011
[INFO] Final Memory: 14M/35M
[INFO] ------------------------------------------------------------------------

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

This plugin is using Doxia 1.1.x. Unless we shade Doxia we will need to bump the prerequisite Maven version to one that uses Doxia 1.1+.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Fixed in [r1238066](http://svn.apache.org/viewvc?view=revision&revision=1238066) by updating the required Maven version to 2.2.1.
