### ISSUE TITLE
[MCHECKSTYLE-250] NPE on tying to load LICENSE.txt resource from non-jar plugin dependencies

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-checkstyle-plugin#562]
**[Konstantin Pokrovsky](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kpokrovsky)** opened **[MCHECKSTYLE-250](https://issues.apache.org/jira/browse/MCHECKSTYLE-250?redirect=false)** and commented

**Steps to reproduce:**
* Add non jar (XML for example) artifact dependency to plugin dependencies section:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-checkstyle-plugin</artifactId>
    <version>2.13</version>
    <dependencies>
        <dependency>
            <groupId>anygroup</groupId>
            <artifactId>anyfile</artifactId>
            <type>xml</type>
        </dependency>
    </dependencies>
</plugin>
```

* Run _checkstyle:check_
  Result:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.13:check (default-cli) on project rt: Execution default-cli of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.13:check failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.13:check (default-cli) on project rt: Execution default-cli of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.13:check failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.13:check failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:115)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.codehaus.plexus.resource.loader.JarHolder.getEntries(JarHolder.java:126)
        at org.codehaus.plexus.resource.loader.JarResourceLoader.loadJar(JarResourceLoader.java:100)
        at org.codehaus.plexus.resource.loader.JarResourceLoader.initialize(JarResourceLoader.java:63)
        at org.codehaus.plexus.resource.loader.JarResourceLoader.getResource(JarResourceLoader.java:141)
        at org.apache.maven.plugin.checkstyle.resource.LicenseResourceManager.getResource(LicenseResourceManager.java:75)
        at org.codehaus.plexus.resource.DefaultResourceManager.getResourceAsFile(DefaultResourceManager.java:91)
        at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.getOverridingProperties(DefaultCheckstyleExecutor.java:520)
        at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.getConfiguration(DefaultCheckstyleExecutor.java:347)
        at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:220)
        at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:532)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        ... 20 common frames omitted
```

**Investigation:**
* _CheckstyleViolationCheckMojo_ forms _CheckstyleExecutorRequest_ for the executor by initializing _licenseArtifacts_ property with all plugin's dependencies.

```java
request.setConsoleListener( getConsoleListener() ).setConsoleOutput( consoleOutput )
    .setExcludes( excludes ).setFailsOnError( failsOnError ).setIncludes( includes )
    .setResourceIncludes( resourceIncludes )
    .setResourceExcludes( resourceExcludes )
    .setIncludeResources( includeResources )
    .setIncludeTestResources( includeTestResources )
    .setIncludeTestSourceDirectory( includeTestSourceDirectory ).setListener( getListener() )
    .setLog( getLog() ).setProject( project ).setSourceDirectories( getSourceDirectories() )
    .setResources( resources )
    .setStringOutputStream( stringOutputStream ).setSuppressionsLocation( suppressionsLocation )
    .setTestSourceDirectories( getTestSourceDirectories() ).setConfigLocation( configLocation )
    .setConfigurationArtifacts( collectArtifacts( "config" ) )
    .setPropertyExpansion( propertyExpansion )
    .setHeaderLocation( headerLocation ).setLicenseArtifacts( collectArtifacts( "license" ) )
    .setCacheFile( cacheFile ).setSuppressionsFileExpression( suppressionsFileExpression )
    .setEncoding( encoding ).setPropertiesLocation( propertiesLocation );
checkstyleExecutor.executeCheckstyle( request );
```

There is a _licence_ hint parameter passed to dependency initializer, but it is actually not used. Leaving all dependencies being uses as the license one.

* _DefaultCheckstyleExecutor_ adds the dependencies to jar search path without checking the dependency type. I think dependencies should be checked for the jar type:

```java
// MCHECKSTYLE-225: load licenses from additional artifacts, not from classpath
if ( additionalArtifacts != null )
{
    for ( Artifact licenseArtifact : additionalArtifacts )
    {
        try
        {
            resourceManager.addSearchPath( "jar", "jar:" + licenseArtifact.getFile().toURI().toURL() );
        }
        catch ( MalformedURLException e )
        {
            // noop
        }
    }
}
```

* Later Plexus _JarResourceLoader_ fails to load the resource from those non jar dependencies:

```java
    public void init()
    {
        try
        {
            URL url = new URL( urlpath );

            conn = (JarURLConnection) url.openConnection();

            conn.setAllowUserInteraction( false );

            conn.setDoInput( true );

            conn.setDoOutput( false );

            conn.connect();

            theJar = conn.getJarFile();
        }
        catch ( IOException ioe )
        {
        }
    }
```

_init()_ silently suppresses _IOException_ thrown on _connect()_ leaving _theJar_ as null which causes NPE later referencing _theJar_'s methods. Definitely another bug, but seems won't be fixed at all since _plexus-resources_ is abandoned.

---

**Affects:** 2.13

**Issue Links:**
- [MCHECKSTYLE-225](https://issues.apache.org/jira/browse/MCHECKSTYLE-225) headerLocation no longer sets checkstyle.header.file

- [MCHECKSTYLE-288](https://issues.apache.org/jira/browse/MCHECKSTYLE-288) NullPointerException during building a multi-module project

1 votes, 7 watchers

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

I have to agree: it would be better to verify if the artifact is actually a jar. But AFAIK just adding an xml as artifact won't work for this plugin, so why would you do so?

**Comment by jira-importer** [comment]
**[Konstantin Pokrovsky](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kpokrovsky)** commented

The initial idea was to install checkstyle config as an artifact. Declare it as a plugin dependency and reuse it straight from repository so that every module could locate the config.

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

why not put the XML in a jar file?

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Bob,

Is there a special reason for you to load the jar as an extension?

The recommended way is to add the jar as a dependency to the plugin (or plugins), as described here:
http://maven.apache.org/plugins/maven-checkstyle-plugin/examples/multi-module-config.html#Configure_the_other_projects_to_use_it

Does that work for you?

**Comment by jira-importer** [comment]
**[J L](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jlch2034)** commented

Adding a couple of extra data points here, which may shed some light. We are running into this issue as well.  I'll spare folks from the stack trace, since it is similar if not identical to the one in the description above.

Dennis, we have a setup just like the one [referenced](http://maven.apache.org/plugins/maven-checkstyle-plugin/examples/multi-module-config.html#Configure_the_other_projects_to_use_it) in your [comment above|#comment-36361].  For what I understand, Bob has a similar setup.

* There is a parent project with pom packaging
* There is build-tools sub module with jar packaging, which contains the checkstyle configuration files.
* There are other sub-modules (5) that have 'build-tools' specified as a dependency.

There may be an additional interaction here with other plugins executed for other lifecycle phases.
* For example, running 'mvn compile checkstyle:check' in the top project succeeds for the first 3 sub modules and deterministically fails when building the 4th submodule.
* Running 'mvn checkstyle:check' seems to succeed.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Hi,

I have just deployed a new 2.15-SNAPSHOT that should fix this. Please give it a try and report back.

http://maven.apache.org/guides/development/guide-testing-development-plugins.html

**Comment by jira-importer** [comment]
**[J L](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jlch2034)** commented

`mvn test-compile checksytle:check` no longer results in an NPE, but runs into MCHECKSTYLE-225.  :S

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15-SNAPSHOT:check (default-cli) on project server: Failed during checkstyle execution: Failed during checkstyle configuration: unable to read /path/to/server/target/checkstyle-checker.xml - unable to parse configuration stream - Property ${checkstyle.header.file} has not been set -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15-SNAPSHOT:check (default-cli) on project raptor-server: Failed during checkstyle execution
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed during checkstyle execution
	at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:539)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.apache.maven.plugin.checkstyle.exec.CheckstyleExecutorException: Failed during checkstyle configuration
	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.getConfiguration(DefaultCheckstyleExecutor.java:450)
	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:218)
	at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:530)
	... 21 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to read /Users/julio/devel/all/cloud-test/raptor-server/target/checkstyle-checker.xml - unable to parse configuration stream - Property ${checkstyle.header.file} has not been set
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:346)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:286)
	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.getConfiguration(DefaultCheckstyleExecutor.java:381)
	... 23 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: unable to parse configuration stream - Property ${checkstyle.header.file} has not been set
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:410)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:338)
	... 25 more
Caused by: org.xml.sax.SAXException: Property ${checkstyle.header.file} has not been set
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader$InternalLoader.startElement(ConfigurationLoader.java:158)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.puppycrawl.tools.checkstyle.api.AbstractLoader.parseInputSource(AbstractLoader.java:99)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.parseInputSource(ConfigurationLoader.java:273)
	at com.puppycrawl.tools.checkstyle.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:397)
	... 26 more
[ERROR]
```
