### ISSUE TITLE
[MCHECKSTYLE-287] checkstyle report throws NPE

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-checkstyle-plugin#588]
**[Thomas Scheffler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=yagee)** opened **[MCHECKSTYLE-287](https://issues.apache.org/jira/browse/MCHECKSTYLE-287?redirect=false)** and commented

I don't know what triggers this bug. Somehow org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.collectArtifacts(String) produces a List which contains the null object. And therefor an exception is thrown here (2.14):

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project oaipmh: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project oaipmh: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.3:site failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.NullPointerException
	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.configureResourceLocator(DefaultCheckstyleExecutor.java:852)
	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:102)
	at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeReport(AbstractCheckstyleReport.java:474)
	at org.apache.maven.plugin.checkstyle.CheckstyleReport.executeReport(CheckstyleReport.java:156)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:219)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:319)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:135)
	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:175)
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:138)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more
```

Looking at the code, you see a null check is done for the list, bit not for elements of that list:

```
// MCHECKSTYLE-225: load licenses from additional artifacts, not from classpath
if ( additionalArtifacts != null )
{
    for ( Artifact licenseArtifact : additionalArtifacts )
    {
        try
        {
            resourceManager.addSearchPath( "jar", "jar:" + licenseArtifact.getFile().toURI().toURL() );
        }
        catch ( MalformedURLException e )
        {
            // noop
        }
    }
}
```

---

**Affects:** 2.13, 2.14

**Attachments:**
- [mcheckstyle-287-demo.tgz](https://issues.apache.org/jira/secure/attachment/12874406/mcheckstyle-287-demo.tgz) (_3.77 kB_)
- [patch1.diff](https://issues.apache.org/jira/secure/attachment/12731903/patch1.diff) (_920 bytes_)
- [projects.tar.gz](https://issues.apache.org/jira/secure/attachment/12781617/projects.tar.gz) (_10.73 kB_)

**Issue Links:**
- [MCHECKSTYLE-294](https://issues.apache.org/jira/browse/MCHECKSTYLE-294) NPE on missing license artifact, not fixed previously
 (_**"contains"**_)
- [MCHECKSTYLE-294](https://issues.apache.org/jira/browse/MCHECKSTYLE-294) NPE on missing license artifact, not fixed previously
 (_**"is duplicated by"**_)

3 votes, 10 watchers

**Comment by jira-importer** [comment]
**[Andreas Höhmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ahoehma)** commented

I fixed the "effect" in my project ...

I have define the checkstyle plugin configuration/depdencies via plugin-management in a "parent-module" ...

```xml
<plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-checkstyle-plugin</artifactId>
   <version>${maven.checkstyle.plugin.version}</version>
   <configuration>
      <configLocation>checkstyle/checkstyle-5.0.xml</configLocation>
      <aggregate>false</aggregate>
   </configuration>
   <dependencies>
      <dependency>
         <groupId>com.puppycrawl.tools</groupId>
         <artifactId>checkstyle</artifactId>
         <version>6.4</version>
      </dependency>
      <dependency>
        <groupId>com.siemens.spice</groupId>
        <artifactId>build-tools</artifactId>
        <version>${build.tools.version}</version> <!-- the module which contains the "checkstyle/checkstyle-5.0.xml" -->
      </dependency>
   </dependencies>
</plugin>
```

also the parent-pom contains the site-plugin configuration ...

```xml
<plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-site-plugin</artifactId>
   <configuration>
      <reportPlugins combine.children="append">
          <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-checkstyle-plugin</artifactId>
              <configuration>
                <configLocation>checkstyle/checkstyle-5.0.xml</configLocation>
                <aggregate>false</aggregate>
              </configuration>
          </plugin>
      </reportPlugins>
  </configuration>
  <dependencies>
    <dependency>
      <groupId>com.siemens.spice</groupId>
      <artifactId>build-tools</artifactId>
       <version>${build.tools.version}</version> <!-- build-tools contains also some site-resources -->
    </dependency>
   </dependencies>
 </plugin>
```

then i have 2 submodules:

A) web application

    mvn site:site is working

B) jar module

    mvn site:site crashed

The only difference is .... **tatata** .. A) is using the checkstyle plugin again for additional checks.

So I tried to add this to the B) plugins ...

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-checkstyle-plugin</artifactId>
</plugin>
```

and ... it works :-)

**Comment by jira-importer** [comment]
**[Michal Koziorowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michallo)** commented

Hi.

I just spot this problem in 2.17 version. I have very similar configuration to [Andreas Höhmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ahoehma) (checkstyle rules configuration file in dependency) but his workaround does not work for me.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Can someone kindly provide a mininal test project? I will have a look at it next week.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Hi,

Do you see these problems if you invoke the Checkstyle plugin separately, i.e. not using 'mvn site:site' but rather 'mvn checkstyle:checkstyle' ? I'm trying to determine whether this is a problem in the Checkstyle plugin or the Site plugin.

**Comment by jira-importer** [comment]
**[Michal Koziorowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michallo)** commented

Hi,

I will search for the project with this error and let you know.

**Comment by jira-importer** [comment]
**[Michal Koziorowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michallo)** commented

mvn checkstyle:checkstyle works. mvn site:site fails.
I remember that I debugged it some time ago and additionalArtifacts list had a null element inside.

**Comment by jira-importer** [comment]
**[Michal Koziorowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michallo)** commented

I think it is minimal project to reproduce.

How to use:
cd NPEProject
cd navservices-configuration
mvn clean install
cd ..
cd checkstyleNPE
mvn -f java-navservices-pom.xml clean install
mvn site:site
mvn site:site <- Second site will throw error.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I just had a look at your project. It uses old versions which I have updated and it is rather convoluted and confusing. The issue is that the first `mvn site` does not even trigger the plugin and the second one does. The suspicious code is:

```
for ( Artifact licenseArtifact : additionalArtifacts )
            {
                try
                {
                    resourceManager.addSearchPath( "jar", "jar:" + licenseArtifact.getFile().toURI().toURL() );
                }
                catch ( MalformedURLException e )
                {
                    // noop
                }
            }
```

The array contains ten elements all of them are null, this should not be the case, moreover the licenseArtifact is null. Therefore, NPE.

Can you trim down your example to a minimal working one?

**Comment by jira-importer** [comment]
**[Lennart Jörelid](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lennartj)** commented

Fixed by PR #88

**Comment by jira-importer** [comment]
**[Lennart Jörelid](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lennartj)** commented

However, the problem stems from another method which attempts to gather all Artifacts which could potentially contain a License.
The call is

```java
final Artifact artifact = (Artifact) plugin.getArtifactMap().get( depKey );
```

... and this returns null for artifacts injected as dependencies to the plugin. When logged using the version pushed in by PR #88, something like the following occurs:

```
[DEBUG] Generating /Users/lj/Development/Projects/Skolverket/Repos/framework/persistence/persistence-spi-jpa/target/site/checkstyle.html
[INFO] Generating "Checkstyle" report           --- maven-checkstyle-plugin:2.18-SNAPSHOT:checkstyle
[DEBUG] Got null CheckstylePlugin Dependency Artifact from key [se.foo:foo-codestyle]. Not including null Artifact. 
[DEBUG] Got null CheckstylePlugin Dependency Artifact from key [se.jguru.nazgul.tools.codestyle:nazgul-codestyle]. Not including null Artifact. 
[DEBUG] Got null CheckstylePlugin Dependency Artifact from key [se.foo:foo-codestyle]. Not including null Artifact. 
[DEBUG] Got null CheckstylePlugin Dependency Artifact from key [se.jguru.nazgul.tools.codestyle:nazgul-codestyle]. Not including null Artifact. 
[DEBUG] executeCheckstyle start headerLocation : LICENSE.txt
[DEBUG] Adding licenceArtifact [com.puppycrawl.tools:checkstyle:6.11.2] to resourceManager.
[DEBUG] Adding licenceArtifact [org.slf4j:jcl-over-slf4j:1.5.6] to resourceManager.
[DEBUG] Adding licenceArtifact [org.slf4j:slf4j-jdk14:1.5.6] to resourceManager.
```

This corresponds to the following configuration of the maven-checkstyle-plugin:

```xml
<plugin>
          <artifactId>maven-checkstyle-plugin</artifactId>
          <version>2.18-SNAPSHOT</version>
          <executions>
            <execution>
              <id>verify</id>
              <phase>package</phase>
              <goals>
                <goal>check</goal>
              </goals>
              <configuration>
                <encoding>UTF-8</encoding>
                <skip>false</skip>
                <configLocation>/codestyle/foo-checkstyle.xml</configLocation>
                <suppressionsLocation>/codestyle/foo-checkstyle-suppressions.xml</suppressionsLocation>
                <failOnViolation>false</failOnViolation>
                <violationSeverity>error</violationSeverity>
                <suppressionsFile>/codestyle/foo-checkstyle-suppressions.xml</suppressionsFile>
              </configuration>
            </execution>
            <execution>
              <id>report</id>
              <goals>
                <goal>checkstyle</goal>
              </goals>
              <configuration>
                <encoding>UTF-8</encoding>
                <skip>false</skip>
                <configLocation>/codestyle/foo-checkstyle.xml</configLocation>
                <suppressionsLocation>/codestyle/foo-checkstyle-suppressions.xml</suppressionsLocation>
                <failOnViolation>false</failOnViolation>
                <violationSeverity>error</violationSeverity>
                <suppressionsFile>/codestyle/foo-checkstyle-suppressions.xml</suppressionsFile>
              </configuration>
            </execution>
          </executions>
          <dependencies>
            <dependency>
              <groupId>com.puppycrawl.tools</groupId>
              <artifactId>checkstyle</artifactId>
              <version>6.19</version>
            </dependency>
            <dependency>
              <groupId>se.foo</groupId>
              <artifactId>foo-codestyle</artifactId>
              <version>1.9.3-SNAPSHOT</version>
            </dependency>
            <dependency>
              <groupId>se.jguru.nazgul.tools.codestyle</groupId>
              <artifactId>nazgul-codestyle</artifactId>
              <version>5.0.1</version>
            </dependency>
            <dependency>
              <groupId>org.slf4j</groupId>
              <artifactId>jcl-over-slf4j</artifactId>
              <version>1.7.20</version>
            </dependency>
            <dependency>
              <groupId>org.slf4j</groupId>
              <artifactId>slf4j-jdk14</artifactId>
              <version>1.7.20</version>
            </dependency>
          </dependencies>
```

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Thanks for the analysis and the PR. Do you actually know why some are `null` here? Is that an error in your point of view? If they are `null`, are we skipping here something?

**Comment by jira-importer** [comment]
**[Lennart Jörelid](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lennartj)** commented

I believe it is an error to encounter `null` values from the method

```
final Artifact artifact = (Artifact) plugin.getArtifactMap().get( depKey );
```

... especially since the artifacts in question are supplied **with** version numbers. Hence, I do not understand why the call to `getArtifactMap` would return a null value. Could you shed some light on this? In which cases do the getArtifactMap method in Plugin return null?

**Comment by jira-importer** [comment]
**[Guillaume Boué](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gboue)** commented

I have trouble reproducing the issue with the attached `projects.tar.gz` (it fails for other reasons of dependencies that couldn't be resolved, I tested with Maven 3.0.5 and 3.3.9 by upgrading the Maven Site Plugin). [Michal Koziorowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michallo), would it be possible to revise the sample project? This looks more of an issue with Maven Core that wouldn't inject the right artifacts into the plugin descriptor.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Something seems to be wrong here:

```
PS D:\Entwicklung\Projekte\mcheckstyle-287-demo> mvn clean install
[INFO] Scanning for projects...
[WARNING] The project mcheckstyle-issue-287:parent:pom:1.0-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Reproduce issue MCHECKSTYLE-287
[INFO] Custom checkstyle rules
[INFO] Dummy project code
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Reproduce issue MCHECKSTYLE-287 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ parent ---
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle-validation) @ parent ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Reproduce issue MCHECKSTYLE-287 .................... FAILURE [  0.531 s]
[INFO] Custom checkstyle rules ............................ SKIPPED
[INFO] Dummy project code ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.630 s
[INFO] Finished at: 2017-06-25T11:21:30+02:00
[INFO] Final Memory: 9M/241M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle-validation) on project parent: Execution checkstyle-validation of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.17 or one of its dependencies could not be resolved: Failure to find mcheckstyle-issue-287:csrules:jar:1.0-SNAPSHOT in http://repository.apache.org/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

**Comment by jira-importer** [comment]
**[Guillaume Boué](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gboue)** commented

[Ed Randall](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=edrandall) I can reproduce the NPE now, thanks for the example. The core issue is that `inherited` is set to `false`, so that the configuration is not propagated to child POM. I suspect this was done to work-around a bug in one of the Shared component of the Site Plugin (MSHARED-616), and this bug is already fixed in current 3.7-SNAPSHOT.
In the sample project, in `parent`, remove

```xml
<plugins>
  <plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-checkstyle-plugin</artifactId>
    <inherited>false</inherited>
  </plugin>
</plugins>
```

and use the Site Plugin 3.7-SNAPSHOT. You'll need to declare a plugin repository with snapshots enabled using the URL https://repository.apache.org/content/repositories/snapshots

```xml
<pluginManagement>
  <plugins>
    <plugin>
      <artifactId>maven-site-plugin</artifactId>
      <version>3.7-SNAPSHOT</version>
    </plugin>
    <!-- ... -->
  </plugins>
</pluginManagement>
```

Then `mvn clean package site` works fine.

**Comment by jira-importer** [comment]
**[Sylwester Lachiewicz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slachiewicz)** commented

I tested the provided sample project (removed inherited=false) with relased maven-site-plugin 3.7 and the error no longer occurs.
Tested with Maven 3.5.2/Windows with latest jdk8u151

Looks like we can close this issue as fixed elsewhere.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Overcome by events and fixed elsewhere.
