### ISSUE TITLE
[MCHECKSTYLE-288] NullPointerException during building a multi-module project

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-checkstyle-plugin#591]
**[Peter Jeszenszky](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jeszy)** opened **[MCHECKSTYLE-288](https://issues.apache.org/jira/browse/MCHECKSTYLE-288?redirect=false)** and commented

A NullPointerException is thrown during the execution of "mvn site" in a multi-module project, that is clearly caused by the Maven Checkstyle Plugin. The problem occurs when version 2.13 or 2.14 of the plugin is used, everything works fine when the plugin version is downgraded to version 2.12. I have attached a project in which the problem occurs.

---

**Affects:** 2.13, 2.14

**Attachments:**
- [geocoder-parent.zip](https://issues.apache.org/jira/secure/attachment/12714703/geocoder-parent.zip) (_21.28 kB_)

**Issue Links:**
- [MCHECKSTYLE-250](https://issues.apache.org/jira/browse/MCHECKSTYLE-250) NPE on tying to load LICENSE.txt resource from non-jar plugin dependencies

1 votes, 7 watchers

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

Please add the stacktrace of the NPE here. Run with mvn -e if necessary

**Comment by jira-importer** [comment]
**[W Herget](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=r007)** commented

Hi!

I've just tried it, and as far as I can tell it does work (at least for me).
Thanks!

**Comment by jira-importer** [comment]
**[Peter Jeszenszky](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jeszy)** commented

Hi,

Version 2.15-SNAPSHOT works fine. Thank you very much!

Waiting for a new release of the plugin:)

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Thanks for testing!

Fixed in [r1666230](http://svn.apache.org/viewvc?view=revision&revision=1666230).

**Comment by jira-importer** [comment]
**[Rob](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rob1)** commented

Using Maven-3.2.3 with maven-checkstyle-plugin-2.17 here and getting exactly the same issue here!

```
[DEBUG]   Fire body() for SetPropertiesRule[]
[DEBUG]   Fire body() for org.apache.velocity.tools.config.XmlFactoryConfigurationRuleSet$PropertyAttributeRule@243135c1
[DEBUG]   Popping body text ''
[DEBUG]   Fire end() for org.apache.velocity.tools.config.XmlFactoryConfigurationRuleSet$PropertyAttributeRule@243135c1
[DEBUG]   Fire end() for SetPropertiesRule[]
[DEBUG] endDocument()
[DEBUG] Velocimacro : added #link(  href name target img position alt border width height title ) : source = org/apache/maven/doxia/siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #image(  img alt border width height title ) : source = org/apache/maven/doxia/siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #banner(  banner id ) : source = org/apache/maven/doxia/siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #links(  links ) : source = org/apache/maven/doxia/siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #breadcrumbs(  breadcrumbs ) : source = org/apache/maven/doxia/siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #displayTree(  display item ) : source = org/apache/maven/doxia/siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #menuItem(  item ) : source = org/apache/maven/doxia/siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #mainMenu(  menus ) : source = org/apache/maven/doxia/siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #copyright(  ) : source = org/apache/maven/doxia/siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #publishDate(  position decorationPublishDate version ) : source = org/apache/maven/doxia/siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #poweredByLogo(  poweredBy ) : source = org/apache/maven/doxia/siterenderer/resources/default-site.vm
[DEBUG] Velocimacro : added #googleAnalytics(  accountId ) : source = org/apache/maven/doxia/siterenderer/resources/default-site.vm
[DEBUG] Multipage report: 0 subreports
[DEBUG] Generating C:\Users\rob\workspace\server\installation\installation-database-install-templates\target\site\checkstyle.html
[INFO] Generating "Checkstyle" report           --- maven-checkstyle-plugin:2.17:checkstyle
[DEBUG] executeCheckstyle start headerLocation : LICENSE.txt
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] installation ............................... SUCCESS [  6.978 s]
[INFO] installation-ant-dependencies .............. SUCCESS [  2.668 s]
[INFO] installation-database-dependencies ......... SUCCESS [  2.343 s]
[INFO] installation-wildfly-dependencies .......... SUCCESS [  3.165 s]
[INFO] installation-sapjco-dependencies ........... SUCCESS [  1.834 s]
[INFO] installation-database-install-templates .... FAILURE [  2.048 s]
[INFO] installation-transdb-install-templates ..... SKIPPED
[INFO] installation-wildfly-install-templates ..... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.848 s
[INFO] Finished at: 2016-01-28T12:32:09+01:00
[INFO] Final Memory: 59M/959M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:site (default-cli) on project installation-database-install-templates: Execution default-cli of goal org.apache.maven.plugins:maven-site-plugin:3.4:site failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:site (default-cli) on project installation-database-install-templates: Execution default-cli of goal org.apache.maven.plugins:maven-site-plugin:3.4:site failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.apache.maven.plugins:maven-site-plugin:3.4:site failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.NullPointerException
	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.configureResourceLocator(DefaultCheckstyleExecutor.java:876)
	at org.apache.maven.plugin.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:102)
	at org.apache.maven.plugin.checkstyle.AbstractCheckstyleReport.executeReport(AbstractCheckstyleReport.java:473)
	at org.apache.maven.plugin.checkstyle.CheckstyleReport.executeReport(CheckstyleReport.java:154)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
	at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:224)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:311)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:129)
	at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:182)
	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:141)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :installation-database-install-templates```
```

Is there any chance to reopen this ticket?

EDIT: mvn --version spits out the following information:

```
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:10+02:00)
Maven home: C:\Program Files\apache-maven-3.2.3
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_66\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"
```

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Hi Rob,

Looking at the stacktraces from the original poster and you, they look different. Your NPE occours in a different place in the code.

Please file a new issue for you problem, and attach a small project that can be used to reproduce your problem.

**Comment by jira-importer** [comment]
**[Andrei Terentiev](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aksian)** commented

Recently I encountered the same problem as Rob (NPE).

The problem arose because one of the newly created modules did not contain the source code yet.

Adding source code or \<packaging>pom\</packaging> solves the problem.
